services:
  cinnamon-vnc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: user

    container_name: cinnamon-vnc

    ports:
      - "${BIND_IP:-127.0.0.1}:5901:5901"
# Commented out so as to prevent noVNC connections
#      - "6080:6080" 

    volumes:
#      - ./data:/data
# The home folder makes user settings persistant. Using /opt/docker-data and not the same folder as the docker compose file is in because of permission issues particular to my machine.
       - /opt/docker-data/cinnamon:/data
       - /opt/docker-data/home:/home/user

    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}

    restart: unless-stopped

    cpus: 2
    mem_limit: 8g

    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
